# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'GitHub Actions'
        required: true
        default: 'GitHub Actions'

env:
  ZOOKEEPER_CONNECTION_STRING : ${{ secrets.ZOOKEEPER_ADDRESS }}

jobs:
  JDK17:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Grant Permission
        run: sudo chmod +x ./mvnw
      - name: Install
        run: ./mvnw -T 4C -B -ntp install -DskipTests
      - name: Run Tests
        run: ./mvnw -B -ntp test
      - name: Upload Code Coverage
        run: bash <(curl -s https://codecov.io/bash)
