# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'GitHub Actions'
        required: true
        default: 'GitHub Actions'

jobs:
  JDK17:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download AWS Corretto
        run: >-
            wget
            https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            distribution: jdkfile
            java-version: '17'
            architecture: x64
            jdkFile: ./amazon-corretto-17-x64-linux-jdk.tar.gz
      - name: Prepare Setup and Initialize
        run: sudo chmod +x setup.sh && sudo chmod +x initialize.sh
      - name: Initialize
        run: sudo ./setup.sh && ./initialize.sh
      - name: Build with Maven
        run: mvn -B -ntp clean test --file pom.xml
      - name: Upload Coverage Report
        run: bash <(curl -s https://codecov.io/bash)
