# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'GitHub Actions'
        required: true
        default: 'GitHub Actions'

jobs:
  JDK17:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove Eclipse Temurin JDK 11
        run: sudo apt remove temurin-11-jdk -y
      - name: Download AWS Corretto
        run: >-
            wget
            https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            distribution: jdkfile
            java-version: '17'
            architecture: x64
            jdkFile: ./amazon-corretto-17-x64-linux-jdk.tar.gz
      - name: Grand Permissions
        run: sudo chmod +x setup.sh && sudo chmod +x initialize.sh && sudo chmod +x .github/scripts/runTests.sh
      - name: Setup and Initialize
        run: sudo ./setup.sh && sudo ./initialize.sh
      - name: Run Tests
        run: sudo .github/scripts/runTests.sh
      - name: Upload Code Coverage
        run: bash <(curl -s https://codecov.io/bash)
