# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'GitHub Actions'
        required: true
        default: 'GitHub Actions'

env:
  MAVEN_OPTS: -Dio.netty.tryReflectionSetAccessible=true

jobs:
  JDK17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          architecture: x64
          
      - name: Grant Permission
        run: sudo chmod +x ./mvnw
        
      - name: Install
        run: ./mvnw -T 4C -B -ntp clean install -DskipTests
        
      - name: Run Tests
        run: ./mvnw -B -ntp clean test
        
      - name: Upload Code Coverage
        run: bash <(curl -s https://codecov.io/bash)
