# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'GitHub Actions'
        required: true
        default: 'GitHub Actions'

jobs:
  BuildJDK11:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prepare Setup and Initialize
        run: sudo chmod +x setup.sh && sudo chmod +x initialize.sh
      - name: Initialize
        run: sudo ./setup.sh && ./initialize.sh
      - name: Build with Maven
        run: sudo mvn -B -ntp test --file pom.xml
      - name: Upload Coverage Report
        run: sudo bash <(curl -s https://codecov.io/bash)


  BuildJDK16:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Prepare Setup and Initialize
        run: sudo chmod +x setup.sh && sudo chmod +x initialize.sh
      - name: Initialize
        run: sudo ./setup.sh && ./initialize.sh
      - name: Build with Maven
        run: sudo mvn -B -ntp test --file pom.xml
