# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'GitHub Actions'
        required: true
        default: 'GitHub Actions'

env:
  MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
  MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}

jobs:
  JDK17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Grant Permission
        run: sudo chmod +x ./mvnw
      - name: Run Tests
        run: ./mvnw -B -ntp clean test --file pom.xml
      - name: Upload Code Coverage
        run: bash <(curl -s https://codecov.io/bash)
