# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'GitHub Actions'
        required: true
        default: 'GitHub Actions'

jobs:
  Jdk17:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Run Tests
        run: mvn -ntp -B test
      - name: Upload Code Coverage
        run: bash <(curl -s https://codecov.io/bash)
